#line 2 "cuobjdump_lexer.c"

#line 4 "cuobjdump_lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer cuobjdump__create_buffer
#define yy_delete_buffer cuobjdump__delete_buffer
#define yy_scan_buffer cuobjdump__scan_buffer
#define yy_scan_string cuobjdump__scan_string
#define yy_scan_bytes cuobjdump__scan_bytes
#define yy_init_buffer cuobjdump__init_buffer
#define yy_flush_buffer cuobjdump__flush_buffer
#define yy_load_buffer_state cuobjdump__load_buffer_state
#define yy_switch_to_buffer cuobjdump__switch_to_buffer
#define yypush_buffer_state cuobjdump_push_buffer_state
#define yypop_buffer_state cuobjdump_pop_buffer_state
#define yyensure_buffer_stack cuobjdump_ensure_buffer_stack
#define yy_flex_debug cuobjdump__flex_debug
#define yyin cuobjdump_in
#define yyleng cuobjdump_leng
#define yylex cuobjdump_lex
#define yylineno cuobjdump_lineno
#define yyout cuobjdump_out
#define yyrestart cuobjdump_restart
#define yytext cuobjdump_text
#define yywrap cuobjdump_wrap
#define yyalloc cuobjdump_alloc
#define yyrealloc cuobjdump_realloc
#define yyfree cuobjdump_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define cuobjdump__create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer cuobjdump__create_buffer
#endif

#ifdef yy_delete_buffer
#define cuobjdump__delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer cuobjdump__delete_buffer
#endif

#ifdef yy_scan_buffer
#define cuobjdump__scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer cuobjdump__scan_buffer
#endif

#ifdef yy_scan_string
#define cuobjdump__scan_string_ALREADY_DEFINED
#else
#define yy_scan_string cuobjdump__scan_string
#endif

#ifdef yy_scan_bytes
#define cuobjdump__scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes cuobjdump__scan_bytes
#endif

#ifdef yy_init_buffer
#define cuobjdump__init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer cuobjdump__init_buffer
#endif

#ifdef yy_flush_buffer
#define cuobjdump__flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer cuobjdump__flush_buffer
#endif

#ifdef yy_load_buffer_state
#define cuobjdump__load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state cuobjdump__load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define cuobjdump__switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer cuobjdump__switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define cuobjdump_push_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state cuobjdump_push_buffer_state
#endif

#ifdef yypop_buffer_state
#define cuobjdump_pop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state cuobjdump_pop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define cuobjdump_ensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack cuobjdump_ensure_buffer_stack
#endif

#ifdef yylex
#define cuobjdump_lex_ALREADY_DEFINED
#else
#define yylex cuobjdump_lex
#endif

#ifdef yyrestart
#define cuobjdump_restart_ALREADY_DEFINED
#else
#define yyrestart cuobjdump_restart
#endif

#ifdef yylex_init
#define cuobjdump_lex_init_ALREADY_DEFINED
#else
#define yylex_init cuobjdump_lex_init
#endif

#ifdef yylex_init_extra
#define cuobjdump_lex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra cuobjdump_lex_init_extra
#endif

#ifdef yylex_destroy
#define cuobjdump_lex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy cuobjdump_lex_destroy
#endif

#ifdef yyget_debug
#define cuobjdump_get_debug_ALREADY_DEFINED
#else
#define yyget_debug cuobjdump_get_debug
#endif

#ifdef yyset_debug
#define cuobjdump_set_debug_ALREADY_DEFINED
#else
#define yyset_debug cuobjdump_set_debug
#endif

#ifdef yyget_extra
#define cuobjdump_get_extra_ALREADY_DEFINED
#else
#define yyget_extra cuobjdump_get_extra
#endif

#ifdef yyset_extra
#define cuobjdump_set_extra_ALREADY_DEFINED
#else
#define yyset_extra cuobjdump_set_extra
#endif

#ifdef yyget_in
#define cuobjdump_get_in_ALREADY_DEFINED
#else
#define yyget_in cuobjdump_get_in
#endif

#ifdef yyset_in
#define cuobjdump_set_in_ALREADY_DEFINED
#else
#define yyset_in cuobjdump_set_in
#endif

#ifdef yyget_out
#define cuobjdump_get_out_ALREADY_DEFINED
#else
#define yyget_out cuobjdump_get_out
#endif

#ifdef yyset_out
#define cuobjdump_set_out_ALREADY_DEFINED
#else
#define yyset_out cuobjdump_set_out
#endif

#ifdef yyget_leng
#define cuobjdump_get_leng_ALREADY_DEFINED
#else
#define yyget_leng cuobjdump_get_leng
#endif

#ifdef yyget_text
#define cuobjdump_get_text_ALREADY_DEFINED
#else
#define yyget_text cuobjdump_get_text
#endif

#ifdef yyget_lineno
#define cuobjdump_get_lineno_ALREADY_DEFINED
#else
#define yyget_lineno cuobjdump_get_lineno
#endif

#ifdef yyset_lineno
#define cuobjdump_set_lineno_ALREADY_DEFINED
#else
#define yyset_lineno cuobjdump_set_lineno
#endif

#ifdef yywrap
#define cuobjdump_wrap_ALREADY_DEFINED
#else
#define yywrap cuobjdump_wrap
#endif

#ifdef yyalloc
#define cuobjdump_alloc_ALREADY_DEFINED
#else
#define yyalloc cuobjdump_alloc
#endif

#ifdef yyrealloc
#define cuobjdump_realloc_ALREADY_DEFINED
#else
#define yyrealloc cuobjdump_realloc
#endif

#ifdef yyfree
#define cuobjdump_free_ALREADY_DEFINED
#else
#define yyfree cuobjdump_free
#endif

#ifdef yytext
#define cuobjdump_text_ALREADY_DEFINED
#else
#define yytext cuobjdump_text
#endif

#ifdef yyleng
#define cuobjdump_leng_ALREADY_DEFINED
#else
#define yyleng cuobjdump_leng
#endif

#ifdef yyin
#define cuobjdump_in_ALREADY_DEFINED
#else
#define yyin cuobjdump_in
#endif

#ifdef yyout
#define cuobjdump_out_ALREADY_DEFINED
#else
#define yyout cuobjdump_out
#endif

#ifdef yy_flex_debug
#define cuobjdump__flex_debug_ALREADY_DEFINED
#else
#define yy_flex_debug cuobjdump__flex_debug
#endif

#ifdef yylineno
#define cuobjdump_lineno_ALREADY_DEFINED
#else
#define yylineno cuobjdump_lineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define cuobjdump_wrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 23
#define YY_END_OF_BUFFER 24
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[386] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   24,   22,   21,    2,   22,   22,   22,    5,
        2,   22,   22,   22,    8,    2,   22,   22,   22,   22,
        7,    2,   22,   22,   22,    9,    2,   22,    9,   22,
        9,    9,    9,    9,    9,   20,   19,    2,   19,   19,
        2,    0,    0,    0,    5,    2,    0,    0,    0,    8,
        2,    0,    0,    0,    7,    0,    0,    2,    0,    0,
        0,    9,    2,    0,    9,    0,    9,    9,    9,    9,
        9,    9,    9,   20,   19,    2,   19,   19,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    9,    0,

        9,    9,    9,    9,    9,    9,    9,    9,   19,   19,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        9,    0,    9,    9,    9,    0,    9,    9,    9,    9,
       19,   19,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    9,   13,    0,    0,    9,    0,    0,    9,
        9,    9,   19,   19,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    9,    0,    0,    9,    0,    0,
        9,    9,    9,   19,   19,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   11,    0,    9,    0,   15,
        9,    9,    9,   20,   19,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        9,    0,    9,    9,    9,   20,   20,   19,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    9,    0,    9,    0,    9,   20,   20,
       19,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    9,    0,    9,    0,
        9,   20,   20,   19,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    9,
        0,    0,   14,    9,   20,   20,   19,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    9,    0,    0,    9,   20,   20,   19,    0,
        0,    0,    1,    0,    0,    0,    1,    0,    0,    0,
        1,    0,    0,    0,    0,    1,    0,    0,    0,    0,
       17,    9,   20,   20,   20,   19,    0,    0,    0,    0,
        0,    0,    0,    0,    6,    0,    0,    0,    0,   20,
       20,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       12,   16,   18,   20,   20,    0,    0,    0,    0,    0,
        0,    0,    0,   10,   20,   20,    4,    3,    4,    3,
        4,    3,    4,    3,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    5,    1,    6,    6,    7,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    9,    1,    1,
       10,    1,    1,    1,   11,   11,   11,   11,   11,   12,
       11,   11,   11,   11,   11,   11,   11,   11,   13,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       14,    1,   15,    1,   16,    1,   17,   18,   19,   20,

       21,   22,   23,   24,   25,   11,   11,   26,   27,   28,
       29,   30,   11,   31,   32,   33,   34,   35,   11,   36,
       11,   37,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[38] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    3,    1,    1,
        3,    3,    3,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3
    } ;

static const flex_int16_t yy_base[404] =
    {   0,
        0,    1,    2,    3,   13,   14,   43,   72,  102,    0,
      139,  169,  723,  724,  724,   11,  705,  688,  717,  724,
       20,   17,    4,  716,  724,   32,   21,   26,  715,   46,
      724,   49,   50,   39,   33,    0,   53,  707,  699,   56,
      684,  685,   41,  693,   38,    0,  199,  214,   70,  149,
       74,  679,  675,  707,  724,   82,  142,  149,  706,  724,
       85,  143,  152,  705,  724,  161,   69,   92,  156,   76,
      155,    0,  153,  697,  673,  700,  685,   74,  671,  670,
      680,  671,  663,    0,  159,    0,  179,  189,  680,  680,
      187,   80,  189,  203,  192,  147,  214,  686,  677,  186,

      670,  672,  662,  687,  657,  661,  668,  670,  219,  225,
      661,  653,  227,  208,  231,  232,  233,  235,  238,  674,
      658,  667,  677,  676,  654,  658,  673,  643,  641,  642,
      236,  239,  645,  659,  245,  242,  246,  247,  248,  250,
      254,  661,  642,  724,  659,  633,  641,  645,  655,  639,
      644,  649,  255,  271,  657,  630,  262,  251,  265,  256,
      284,  272,  274,  649,  654,  653,  635,  634,  636,  649,
      630,  630,  620,  285,  283,  264,  616,  277,  279,  293,
      292,  294,  296,  297,  638,  724,  616,  630,  611,  724,
      619,  612,  609,  281,  298,  615,  607,  614,  300,  305,

      307,  313,  314,  315,  316,  317,  318,  326,  628,  605,
      604,  612,  613,  629,  607,  605,  597,  327,  607,  592,
      598,  306,  330,  333,  334,  338,  340,  341,  342,  343,
      350,  616,  600,  599,  619,  591,  611,  591,  597,  582,
      341,  613,  612,  587,  351,  354,  356,  357,  361,  364,
      368,  373,  370,  365,  604,  584,  575,  586,  606,  605,
      580,  603,  602,  373,  586,  585,  571,  379,  380,  382,
      383,  384,  385,  386,  387,   38,  388,  592,  573,  579,
      571,  588,  724,  565,  577,  576,  387,  565,  564,  589,
      393,  397,  588,  401,  404,  587,  405,  406,  408,  586,

      578,  583,  582,  563,  580,  435,  554,  553,  450,  561,
      560,  576,  724,  407,  409,  575,  724,  422,  428,  574,
      724,  443,  453,  454,  573,  724,  565,  564,  563,  543,
      724,  473,  551,  550,  566,  488,  547,  546,  463,  464,
      465,  478,  491,  492,  724,  556,  539,  536,  506,  475,
      459,  463,  462,  415,  497,  498,  501,  502,  505,  460,
      724,  724,  724,  460,  449,  444,  440,  429,  425,  420,
      418,  410,  199,  724,  195,  159,  724,  724,  724,  724,
      724,  724,  724,  724,  724,  514,  517,  520,  523,  526,
      529,  532,  535,   83,  538,  541,  544,  547,  550,  553,

      556,  559,  562
    } ;

static const flex_int16_t yy_def[404] =
    {   0,
      386,  386,  387,  387,  388,  388,  389,  389,  385,    9,
      390,  390,  385,  385,  385,  385,  385,  385,  391,  385,
      391,  391,  391,  392,  385,  392,  392,  392,  393,  393,
      385,  393,  393,  393,  393,  394,  394,  385,  394,  385,
      394,  394,  394,  394,  394,  395,  396,  396,   48,   48,
      385,  385,  385,  391,  385,  391,  391,  391,  392,  385,
      392,  392,  392,  393,  385,  393,  393,  393,  393,  393,
      393,  394,  394,  385,  394,  385,  394,  394,  394,  394,
      394,  394,  394,  395,   48,   48,   48,   48,  385,  385,
      391,  391,  392,  392,  393,  393,  393,  385,  394,  385,

      394,  394,  394,  394,  394,  394,  394,  394,   48,   48,
      385,  385,  391,  391,  392,  392,  393,  393,  393,  385,
      394,  385,  394,  394,  394,  385,  394,  394,  394,  394,
       48,   48,  385,  385,  391,  391,  392,  392,  393,  393,
      393,  385,  394,  385,  385,  385,  394,  385,  385,  394,
      394,  394,   48,   48,  385,  385,  391,  391,  392,  392,
      393,  393,  393,  385,  394,  385,  385,  394,  385,  385,
      394,  394,  394,   48,   48,  385,  385,  391,  391,  392,
      392,  393,  393,  393,  385,  385,  385,  394,  385,  385,
      394,  394,  394,  395,   48,  385,  385,  385,  391,  391,

      391,  392,  392,  392,  393,  393,  393,  393,  385,  385,
      394,  385,  394,  394,  394,  395,  395,   48,  385,  385,
      385,  391,  391,  391,  392,  392,  392,  393,  393,  393,
      393,  385,  385,  394,  385,  394,  385,  394,  395,  395,
       48,  385,  385,  385,  391,  391,  391,  392,  392,  392,
      393,  393,  393,  393,  385,  385,  394,  385,  394,  385,
      394,  395,  395,   48,  385,  385,  385,  391,  391,  391,
      392,  392,  392,  393,  393,  393,  393,  385,  385,  394,
      385,  385,  385,  394,  395,  395,   48,  385,  385,  397,
      391,  391,  398,  392,  392,  399,  393,  393,  393,  400,

      385,  385,  394,  385,  385,  401,  395,  395,  402,  385,
      385,  397,  385,  391,  391,  398,  385,  392,  392,  399,
      385,  393,  393,  393,  400,  385,  385,  385,  385,  385,
      385,  401,  395,  395,  403,  402,  385,  385,  391,  391,
      392,  392,  393,  393,  385,  385,  385,  385,  385,  395,
      395,  385,  385,  391,  391,  392,  392,  393,  393,  385,
      385,  385,  385,  395,  395,  385,  385,  391,  391,  392,
      392,  393,  393,  385,  395,  395,  385,  385,  385,  385,
      385,  385,  385,  385,    0,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,

      385,  385,  385
    } ;

static const flex_int16_t yy_nxt[762] =
    {   0,
      385,  385,   15,   15,   20,   20,   55,   16,   16,   21,
       21,   17,   17,   22,   22,   25,   25,   51,   51,   55,
       26,   26,   55,   60,   27,   27,   56,   56,   60,   18,
       18,   23,   23,   57,   60,   65,   58,   62,   61,   61,
       65,   65,   28,   28,   30,   31,   30,   66,   65,   66,
       32,   65,   65,  299,   33,   68,   68,   79,   63,   73,
       73,   34,   76,   76,   67,   71,   69,   70,   82,   80,
       83,   65,   35,   30,   31,   30,   85,   85,   65,   32,
       51,   51,   55,   33,   55,   72,   87,   60,   56,   56,
       34,   61,   61,  102,   65,   96,  114,   70,   68,   68,

      103,   35,   14,   14,   15,   14,   14,   14,   36,   37,
       14,   38,   36,   39,   36,   40,   14,   36,   41,   36,
       42,   36,   36,   36,   36,   43,   44,   36,   36,   36,
       36,   45,   36,   36,   36,   36,   36,   36,   36,   46,
       46,   15,   46,   46,   55,   60,   48,   46,   46,   65,
       49,   55,   46,   46,   60,   85,   85,   65,   65,   73,
       73,  378,   66,   65,   66,   85,   85,  118,   50,   46,
       46,   15,   46,   46,   91,   93,   48,   46,   46,   67,
       49,   88,   46,   46,   92,   85,   85,   94,   95,   55,
       97,   60,  122,  122,   65,   85,   85,  377,   50,   84,

       84,  384,   84,   84,  113,   60,  115,   84,   84,  117,
       55,  109,   84,   84,   84,   84,   65,   84,   84,  116,
       86,   86,   84,   84,  110,   85,   85,   84,   84,   55,
      119,   85,   85,   60,   60,   65,  131,   65,  140,  136,
       65,  132,   85,   85,   55,   85,   85,   55,   60,   60,
       65,  135,   65,   55,  158,  137,   65,  139,   60,  160,
      153,   85,   85,  138,   55,  178,  163,   60,  180,  141,
      154,  162,  157,  159,   65,  161,   65,   85,   85,   55,
      179,   55,  174,  175,  196,  181,   65,  182,  194,   85,
       85,   85,   85,  197,   60,   60,   65,  199,   65,   65,

      183,  216,   55,  184,   85,   85,  200,   55,   55,   55,
      217,  201,  195,  202,  205,   60,   60,   60,   65,   65,
       65,  230,  203,  206,  204,  222,  207,  245,   65,  208,
      218,  224,   55,   85,   85,   55,   60,  223,  225,  227,
       60,  228,   60,   65,   65,   65,  226,   85,   85,  229,
      231,  241,   65,   55,  268,  248,   55,  269,   55,   60,
      271,  247,  251,   60,  272,  246,   60,   65,  250,  264,
       65,  274,   65,  249,  253,   65,  275,  252,  254,   85,
       85,   55,   55,  270,   55,   60,   60,   60,   65,   65,
       65,  273,  277,   85,   85,   55,  276,  291,  292,   55,

      287,  294,  295,   60,  297,  298,   60,   65,   65,   55,
       65,   55,  383,  293,  324,  324,  296,   55,  309,  300,
      382,  314,  381,  368,   60,  315,  339,  380,  340,  318,
       60,  379,  319,  322,  323,  312,  312,  313,  312,  312,
      312,  341,  378,  312,  312,   65,  377,  342,  312,  312,
      335,  335,  313,  335,  335,   65,  345,  376,  335,  335,
      324,  324,  343,  335,  335,   55,   55,   60,  375,  374,
      367,  366,  344,  312,  312,  313,  312,  312,  312,  365,
       60,  312,  312,  354,  355,  356,  312,  312,  335,  335,
      313,  335,  335,   65,   65,  364,  335,  335,  357,   55,

       60,  335,  335,   60,   65,  369,  370,   65,  363,  371,
      372,  358,  359,  373,   14,   14,   14,   19,   19,   19,
       24,   24,   24,   29,   29,   29,   47,   47,   47,   54,
       54,   54,   59,   59,   59,   64,   64,   64,   84,  362,
       84,   85,  361,   85,  312,  312,  312,  316,  316,  316,
      320,  320,  320,  325,  325,  325,  332,  332,  332,  336,
      336,  336,  335,  335,  335,  360,  353,  352,  313,  351,
      350,  349,  348,  347,  346,  326,  321,  317,  313,  338,
      337,  334,  333,  331,  330,  329,  328,  327,  326,  321,
      317,  313,  311,  310,  308,  307,  306,  305,  304,  303,

      302,  301,  290,  289,  288,  286,  285,  284,  283,  282,
      281,  280,  279,  278,  267,  266,  265,  263,  262,  261,
      260,  259,  258,  257,  256,  255,  244,  243,  242,  240,
      239,  238,  237,  236,  235,  234,  233,  232,  221,  220,
      219,  215,  214,  213,  212,  211,  210,  209,  198,  193,
      192,  191,  190,  189,  188,  187,  186,  176,  185,  177,
      176,  173,  172,  171,  170,  169,  168,  167,  166,  165,
      164,  156,  155,  152,  151,  150,  149,  148,  147,  146,
      145,  144,  143,  142,  134,  133,  130,  129,  128,  127,
      126,  125,  124,  123,  121,  120,  112,  111,  108,  107,

      106,  105,  104,  101,  100,   99,   98,   65,   60,   55,
       90,   89,   81,   78,   77,   75,   74,   65,   60,   55,
       53,   52,  385,   13,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385
    } ;

static const flex_int16_t yy_chk[762] =
    {   0,
        0,    0,    1,    2,    3,    4,   23,    1,    2,    3,
        4,    1,    2,    3,    4,    5,    6,   16,   16,   22,
        5,    6,   21,   27,    5,    6,   21,   21,   28,    1,
        2,    3,    4,   22,   26,   35,   23,   27,   26,   26,
      276,   34,    5,    6,    7,    7,    7,   30,   30,   30,
        7,   32,   33,  276,    7,   32,   32,   43,   28,   37,
       37,    7,   40,   40,   30,   35,   33,   34,   45,   43,
       45,   67,    7,    8,    8,    8,   49,   49,   70,    8,
       51,   51,   92,    8,   56,  394,   49,   61,   56,   56,
        8,   61,   61,   78,   68,   70,   92,   67,   68,   68,

       78,    8,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,   11,
       11,   11,   11,   11,   57,   62,   11,   11,   11,   96,
       11,   58,   11,   11,   63,   50,   50,   71,   69,   73,
       73,  376,   66,   66,   66,   85,   85,   96,   11,   12,
       12,   12,   12,   12,   57,   62,   12,   12,   12,   66,
       12,   50,   12,   12,   58,   87,   87,   63,   69,   91,
       71,   93,  100,  100,   95,   88,   88,  375,   12,   47,

       47,  373,   47,   47,   91,   94,   93,   47,   47,   95,
      114,   87,   47,   47,   48,   48,   97,   48,   48,   94,
       48,   48,   48,   48,   88,  109,  109,   48,   48,  113,
       97,  110,  110,  115,  116,  117,  109,  118,  118,  114,
      119,  110,  131,  131,  136,  132,  132,  135,  137,  138,
      139,  113,  140,  158,  136,  115,  141,  117,  160,  138,
      131,  153,  153,  116,  157,  157,  141,  159,  159,  119,
      132,  140,  135,  137,  162,  139,  163,  154,  154,  178,
      158,  179,  153,  154,  176,  160,  161,  161,  174,  175,
      175,  174,  174,  176,  181,  180,  182,  178,  183,  184,

      162,  194,  199,  163,  195,  195,  178,  200,  222,  201,
      194,  179,  175,  180,  182,  202,  203,  204,  205,  206,
      207,  207,  180,  182,  181,  199,  183,  222,  208,  184,
      195,  201,  223,  218,  218,  224,  225,  200,  202,  204,
      226,  205,  227,  228,  229,  230,  203,  241,  241,  206,
      208,  218,  231,  245,  245,  225,  246,  246,  247,  248,
      248,  224,  228,  249,  249,  223,  250,  254,  227,  241,
      251,  251,  253,  226,  230,  252,  252,  229,  231,  264,
      264,  268,  269,  247,  270,  271,  272,  273,  274,  275,
      277,  250,  254,  287,  287,  291,  253,  268,  269,  292,

      264,  271,  272,  294,  274,  275,  295,  297,  298,  314,
      299,  315,  372,  270,  299,  299,  273,  354,  287,  277,
      371,  291,  370,  354,  318,  292,  314,  369,  315,  294,
      319,  368,  295,  297,  298,  306,  306,  306,  306,  306,
      306,  318,  367,  306,  306,  322,  366,  319,  306,  306,
      309,  309,  309,  309,  309,  323,  324,  365,  309,  309,
      324,  324,  322,  309,  309,  339,  340,  341,  364,  360,
      353,  352,  323,  332,  332,  332,  332,  332,  332,  351,
      342,  332,  332,  339,  340,  341,  332,  332,  336,  336,
      336,  336,  336,  343,  344,  350,  336,  336,  342,  355,

      356,  336,  336,  357,  358,  355,  356,  359,  349,  357,
      358,  343,  344,  359,  386,  386,  386,  387,  387,  387,
      388,  388,  388,  389,  389,  389,  390,  390,  390,  391,
      391,  391,  392,  392,  392,  393,  393,  393,  395,  348,
      395,  396,  347,  396,  397,  397,  397,  398,  398,  398,
      399,  399,  399,  400,  400,  400,  401,  401,  401,  402,
      402,  402,  403,  403,  403,  346,  338,  337,  335,  334,
      333,  330,  329,  328,  327,  325,  320,  316,  312,  311,
      310,  308,  307,  305,  304,  303,  302,  301,  300,  296,
      293,  290,  289,  288,  286,  285,  284,  282,  281,  280,

      279,  278,  267,  266,  265,  263,  262,  261,  260,  259,
      258,  257,  256,  255,  244,  243,  242,  240,  239,  238,
      237,  236,  235,  234,  233,  232,  221,  220,  219,  217,
      216,  215,  214,  213,  212,  211,  210,  209,  198,  197,
      196,  193,  192,  191,  189,  188,  187,  185,  177,  173,
      172,  171,  170,  169,  168,  167,  166,  165,  164,  156,
      155,  152,  151,  150,  149,  148,  147,  146,  145,  143,
      142,  134,  133,  130,  129,  128,  127,  126,  125,  124,
      123,  122,  121,  120,  112,  111,  108,  107,  106,  105,
      104,  103,  102,  101,   99,   98,   90,   89,   83,   82,

       81,   80,   79,   77,   76,   75,   74,   64,   59,   54,
       53,   52,   44,   42,   41,   39,   38,   29,   24,   19,
       18,   17,   13,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[24] =
    {   0,
1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 
    0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "cuobjdump.l"
/*
// Copyright (c) 2011-2012, Andrew Boktor
// The University of British Columbia
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// Redistributions of source code must retain the above copyright notice, this
// list of conditions and the following disclaimer.
// Redistributions in binary form must reproduce the above copyright notice, this
// list of conditions and the following disclaimer in the documentation and/or
// other materials provided with the distribution.
// Neither the name of The University of British Columbia nor the names of its
// contributors may be used to endorse or promote products derived from this
// software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#line 30 "cuobjdump.l"
	/*Lex file for output of cuobjdump*/
#include <stdio.h>
#include <string.h>
#include "cuobjdump_parser.h"

#define YY_NEVER_INTERACTIVE 1
#define YY_NO_INPUT
#define YY_NO_TOP_STATE

#define YYDEBUG 1

#define yylval cuobjdump_lval

void cuobjdump_error(const char*);
#line 1070 "cuobjdump_lexer.c"

#line 1072 "cuobjdump_lexer.c"

#define INITIAL 0
#define ptxcode 1
#define sasscode 2
#define elfcode 3
#define header 4
#define endheader 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state ( int _new_state );
    
    static void yy_pop_state ( void );
    
    static int yy_top_state ( void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 64 "cuobjdump.l"



#line 1306 "cuobjdump_lexer.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 386 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 385 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 67 "cuobjdump.l"

	YY_BREAK
case 2:
YY_RULE_SETUP
#line 68 "cuobjdump.l"
yylval.string_value = strdup(yytext); return DECIMAL;
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 71 "cuobjdump.l"
{
	yy_push_state(ptxcode);
	yy_push_state(header);
	yylval.string_value = strdup(yytext);
	return PTXHEADER;
}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 77 "cuobjdump.l"
{
	yy_push_state(elfcode);
	yy_push_state(header);
	yylval.string_value = strdup(yytext);
	return ELFHEADER;
}
	YY_BREAK
/*PTX code tokens*/
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 84 "cuobjdump.l"
yylval.string_value = strdup(yytext); return PTXLINE;
	YY_BREAK
/*ELF code tokens*/
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 87 "cuobjdump.l"
{
	BEGIN(sasscode); 
	yylval.string_value = strdup(yytext); 
	return SASSLINE;
}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 92 "cuobjdump.l"
yylval.string_value = strdup(yytext); return ELFLINE;
	YY_BREAK
/*SASS code tokens*/
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 95 "cuobjdump.l"
yylval.string_value = strdup(yytext); return SASSLINE;
	YY_BREAK
/*Header tokens*/
case 9:
YY_RULE_SETUP
#line 98 "cuobjdump.l"
yylval.string_value = strdup(yytext); return IDENTIFIER;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 99 "cuobjdump.l"
return H_SEPARATOR;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 100 "cuobjdump.l"
return H_ARCH;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 101 "cuobjdump.l"
return H_CODEVERSION;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 102 "cuobjdump.l"
return CODEVERSION;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 103 "cuobjdump.l"
return H_PRODUCER;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 104 "cuobjdump.l"
return H_HOST;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 105 "cuobjdump.l"
return H_COMPILESIZE;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 106 "cuobjdump.l"
BEGIN(endheader); return H_IDENTIFIER;
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 107 "cuobjdump.l"

	YY_BREAK
/* Looking for the identifier (filename) then the header is done */
case 19:
YY_RULE_SETUP
#line 110 "cuobjdump.l"
yylval.string_value = strdup(yytext); yy_pop_state(); /*return FILENAME; */
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 111 "cuobjdump.l"
yylval.string_value = strdup(yytext); yy_pop_state(); /*return FILENAME;*/
	YY_BREAK
case 21:
/* rule 21 can match eol */
YY_RULE_SETUP
#line 114 "cuobjdump.l"
return NEWLINE;
	YY_BREAK
/*Reached end of file*/
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ptxcode):
case YY_STATE_EOF(sasscode):
case YY_STATE_EOF(elfcode):
case YY_STATE_EOF(header):
case YY_STATE_EOF(endheader):
#line 117 "cuobjdump.l"
BEGIN(INITIAL);return 0;
	YY_BREAK
/*No other rule matched. Throw an error*/
case 22:
YY_RULE_SETUP
#line 120 "cuobjdump.l"
cuobjdump_error("Invalid token");
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 122 "cuobjdump.l"
ECHO;
	YY_BREAK
#line 1523 "cuobjdump_lexer.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 386 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 386 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 385);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    static int yy_top_state  (void)
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        yyfree( (yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 122 "cuobjdump.l"

void cuobjdump_error(const char* message)
{
	printf("   "); printf(message); printf(" near \""); printf(yytext); printf("\"");
	printf(" on line "); 
	char line[5]; sprintf(line, "%i", yylineno); printf(line);
	printf("\n");
}

